<a href="https://colab.research.google.com/github/taicichin/Student-Depression-2025/blob/main/Student_Depression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/taicichin/Student-Depression-2025/refs/heads/main/Depression%20Student%20Dataset.csv')
df.head()

,Gender,Age,Academic Pressure,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Male,28,2.0,4.0,7-8 hours,Moderate,Yes,9,2,Yes,No
1,Male,28,4.0,5.0,5-6 hours,Healthy,Yes,7,1,Yes,No
2,Male,25,1.0,3.0,5-6 hours,Unhealthy,Yes,10,4,No,Yes
3,Male,23,1.0,4.0,More than 8 hours,Unhealthy,Yes,7,2,Yes,No
4,Female,31,1.0,5.0,More than 8 hours,Healthy,Yes,4,2,Yes,No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502 entries, 0 to 501
Data columns (total 11 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gender                                 502 non-null    object
 1   Age                                    502 non-null    int64
 2   Academic Pressure                      502 non-null    float64
 3   Study Satisfaction                     502 non-null    float64
 4   Sleep Duration                         502 non-null    object
 5   Dietary Habits                         502 non-null    object
 6   Have you ever had suicidal thoughts ?  502 non-null    object
 7   Study Hours                            502 non-null    int64
 8   Financial Stress                       502 non-null    int64
 9   Family History of Mental Illness       502 non-null    object
 10  Depression                             502 non-null    object
dtypes: float64(2), int64(3), object(6)
memory usage: 43.3+ KB

In [5]:
df.isnull().sum()

Gender                                   0
Age                                      0
Academic Pressure                        0
Study Satisfaction                       0
Sleep Duration                           0
Dietary Habits                           0
Have you ever had suicidal thoughts ?    0
Study Hours                              0
Financial Stress                         0
Family History of Mental Illness         0
Depression                               0
dtype: int64

In [6]:
df.describe()

,Age,Academic Pressure,Study Satisfaction,Study Hours,Financial Stress
count,502.000000,502.000000,502.000000,502.000000,502.000000
mean,26.241036,3.003984,3.075697,6.404382,2.928287
std,4.896501,1.390007,1.373490,3.742434,1.425053
min,18.000000,1.000000,1.000000,0.000000,1.000000
25%,22.000000,2.000000,2.000000,3.000000,2.000000
50%,26.500000,3.000000,3.000000,7.000000,3.000000
75%,30.000000,4.000000,4.000000,10.000000,4.000000
max,34.000000,5.000000,5.000000,12.000000,5.000000

In [7]:
df['Sleep Duration'].unique()

array(['7-8 hours', '5-6 hours', 'More than 8 hours', 'Less than 5 hours'],
      dtype=object)

In [9]:
dic = {'Less than 5 hours' : 1,'5-6 hours': 2, '7-8 hours' : 3, 'More than 8 hours': 4}

In [10]:
df['Sleep Duration'] = df['Sleep Duration'].map(dic)

In [11]:
df.head()

,Gender,Age,Academic Pressure,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Male,28,2.0,4.0,3,Moderate,Yes,9,2,Yes,No
1,Male,28,4.0,5.0,2,Healthy,Yes,7,1,Yes,No
2,Male,25,1.0,3.0,2,Unhealthy,Yes,10,4,No,Yes
3,Male,23,1.0,4.0,4,Unhealthy,Yes,7,2,Yes,No
4,Female,31,1.0,5.0,4,Healthy,Yes,4,2,Yes,No